/*
** Pipeline code.
*/

stage('Dependencies containers creation') {
  parallel 'centos7 dependencies': {
    node {
      dir('centreon-collect-centos7') {
        checkout scm
        dir ('ci/docker') {
          sh 'curl -o ds.tar.gz https://downloads.dockerslim.com/releases/1.36.2/dist_linux.tar.gz && tar -xzf ds.tar.gz && sudo mv dist_linux/* /usr/bin'
          sh 'docker build . -f Dockerfile.collect-centos7-dependencies -t registry.centreon.com/centreon-collect-centos7-dependencies:21.10'
          sh 'docker push registry.centreon.com/centreon-collect-centos7-dependencies:21.10'
          sh 'docker-slim build --dockerfile Dockerfile.collect-centos7-dependencies --tag registry.centreon.com/centreon-collect-centos7-dependencies-slim:21.10 --http-probe-off .'
          sh 'docker push registry.centreon.com/centreon-collect-centos7-dependencies-slim:21.10'
        }
      }
    }
  },
  'debian dependencies': {
    node {
      dir('centreon-collect-debian') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build . -f Dockerfile.collect-debian-dependencies -t registry.centreon.com/centreon-collect-debian-dependencies:21.10'
          sh 'docker push registry.centreon.com/centreon-collect-debian-dependencies:21.10'
        }
      }
    }
  },
  'centos8 dependencies': {
    node {
      dir('centreon-collect-centos8') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build . -f Dockerfile.collect-centos8-dependencies -t registry.centreon.com/centreon-collect-centos8-dependencies:21.10'
          sh 'docker push registry.centreon.com/centreon-collect-centos8-dependencies:21.10'
        }
      }
    }
  }
}