/*
**  Copyright 2009 MERETHIS
**  This file is part of CentreonBroker.
**
**  CentreonBroker is free software: you can redistribute it and/or modify it
**  under the terms of the GNU General Public License as published by the Free
**  Software Foundation, either version 2 of the License, or (at your option)
**  any later version.
**
**  CentreonBroker is distributed in the hope that it will be useful, but
**  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
**  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
**  for more details.
**
**  You should have received a copy of the GNU General Public License along
**  with CentreonBroker.  If not, see <http://www.gnu.org/licenses/>.
**
**  For more information : contact@centreon.com
*/

#ifndef LOGGING_H_
# define LOGGING_H_

# include <boost/thread/mutex.hpp>
# include <fstream>
# include <list>
# include <string>

namespace               CentreonBroker
{
  /**
   *  \class Logging logging.h "logging.h"
   *  \brief Logging facility.
   *
   *  All messages generated by CentreonBroker are sent through this facility.
   *  Those messages are broadcasted to all configured streams. Each stream can
   *  receive only specific messages like informational (INFO), debug (DEBUG)
   *  or error (ERROR).
   */
  class                 Logging
  {
   public:
    enum                MsgType
    {
      DEBUG = 1,
      ERROR = 2,
      INFO = 4
    };

   private:
    class               Output
    {
     private:
      void              Clean();
      void              InternalCopy(const Logging::Output& output);

     public:
      std::string       filename_;
      int               flags_;
      std::ofstream*    stream_;

                        Output();
                        Output(const Output& output);
                        ~Output() throw ();
      Output&           operator=(const Output& output);
    };

    boost::mutex        mutex_;
    std::list<Output>   outputs_;
    int                 stderr_flags_;
    int                 stdout_flags_;
    int                 syslog_flags_;
                        Logging(const Logging& logging);
    Logging&            operator=(const Logging& logging);
    void                LogBase(const char* str, MsgType msg_type) throw ();

   public:
                        Logging();
                        ~Logging() throw ();
# ifndef NDEBUG
    void                LogDebug(const char* str) throw ();
# endif /* !NDEBUG */
    void                LogError(const char* str) throw ();
    void                LogInFile(const char* filename, int log_flags);
    void                LogInfo(const char* str) throw ();
    void                LogInSyslog(int log_flags) throw ();
    void                LogToStderr(int log_flags) throw ();
    void                LogToStdout(int log_flags) throw ();
  };

  extern Logging        logging;
}

#endif /* !LOGGING_H_ */
