-- The PostgreSQL schema is a quick and dirty port of MySQL's.
-- Present for test purposes only.

CREATE TABLE "acknowledgements" (
  "id" serial,
  "instance_id" smallint NOT NULL default '0',
  "host_id" smallint  default NULL,
  "service_id" smallint  default NULL,
  "entry_time" int NOT NULL,
  "acknowledgement_type" smallint NOT NULL default '0',
  "state" smallint NOT NULL default '0',
  "author_name" varchar(64) NOT NULL default '',
  "comment_data" varchar(255) NOT NULL default '',
  "is_sticky" smallint NOT NULL default '0',
  "persistent_comment" smallint NOT NULL default '0',
  "notify_contacts" smallint NOT NULL default '0',
  PRIMARY KEY  ("id")
);
CREATE TABLE "comment" (
  "id" serial,
  "instance_id" int NOT NULL default '0',
  "author_name" varchar(255) NOT NULL default '',
  "comment_data" text NOT NULL,
  "comment_time" int NOT NULL,
  "comment_type" smallint NOT NULL default '0',
  "deletion_time" int NOT NULL,
  "entry_time" int NOT NULL,
  "entry_type" smallint NOT NULL default '0',
  "expire_time" int NOT NULL,
  "expires" boolean NOT NULL default '0',
  "host_name" varchar(255) default NULL,
  "internal_comment_id" int NOT NULL default '0',
  "persistent" boolean NOT NULL default '0',
  "service_description" varchar(160) default NULL,
  "source" smallint NOT NULL default '0',
  PRIMARY KEY  ("id")
);
CREATE TABLE "connection_info" (
  "id" serial,
  "instance_id" int NOT NULL default '0',
  "agent_name" varchar(32) NOT NULL default '',
  "agent_version" varchar(8) NOT NULL default '',
  "connect_source" varchar(16) NOT NULL default '',
  "connect_type" varchar(16) NOT NULL default '',
  "connect_time" int NOT NULL,
  "disconnect_time" int NOT NULL,
  "last_checkin_time" int NOT NULL,
  "data_start_time" int NOT NULL,
  "data_end_time" int NOT NULL,
  "bytes_processed" int NOT NULL default '0',
  "lines_processed" int NOT NULL default '0',
  "entries_processed" int NOT NULL default '0',
  PRIMARY KEY  ("id")
);
CREATE TABLE "customvariables" (
  "id" serial,
  "instance_id" smallint NOT NULL default '0',
  "object_id" int NOT NULL default '0',
  "config_type" smallint NOT NULL default '0',
  "has_been_modified" smallint NOT NULL default '0',
  "varname" varchar(255) NOT NULL default '',
  "varvalue" varchar(255) NOT NULL default '',
  PRIMARY KEY  ("id"),
  UNIQUE ("object_id","config_type","varname")
);
CREATE TABLE "customvariablestatus" (
  "id" serial,
  "instance_id" smallint NOT NULL default '0',
  "object_id" int NOT NULL default '0',
  "status_update_time" int NOT NULL,
  "has_been_modified" smallint NOT NULL default '0',
  "varname" varchar(255) NOT NULL default '',
  "varvalue" varchar(255) NOT NULL default '',
  PRIMARY KEY ("id"),
  UNIQUE ("object_id","varname")
);
CREATE TABLE "eventhandlers" (
  "id" serial,
  "instance_id" smallint NOT NULL default '0',
  "host_id" smallint  default NULL,
  "service_id" smallint  default NULL,
  "eventhandler_type" smallint NOT NULL default '0',
  "state" smallint NOT NULL default '0',
  "state_type" smallint NOT NULL default '0',
  "start_time" int NOT NULL,
  "end_time" int NOT NULL,
  "command_args" varchar(255) NOT NULL default '',
  "command_line" varchar(255) NOT NULL default '',
  "timeout" smallint NOT NULL default '0',
  "early_timeout" smallint NOT NULL default '0',
  "execution_time" double precision NOT NULL default '0',
  "return_code" smallint NOT NULL default '0',
  "output" varchar(255) NOT NULL default '',
  PRIMARY KEY ("id"),
  UNIQUE ("instance_id","start_time")
);
CREATE TABLE "flappinghistory" (
  "id" serial,
  "instance_id" smallint NOT NULL default '0',
  "host_id" smallint  NOT NULL,
  "service_id" smallint  NOT NULL,
  "event_time" int NOT NULL,
  "event_type" smallint NOT NULL default '0',
  "reason_type" smallint NOT NULL default '0',
  "flapping_type" smallint NOT NULL default '0',
  "percent_state_change" double precision NOT NULL default '0',
  "low_threshold" double precision NOT NULL default '0',
  "high_threshold" double precision NOT NULL default '0',
  "comment_time" int NOT NULL,
  "internal_comment_id" int NOT NULL default '0',
  PRIMARY KEY ("id")
);
CREATE TABLE "host" (
  "id" serial,
  "instance_id" int NOT NULL default '0',
  "host_name" varchar(255) default NULL,
  "alias" varchar(100) NOT NULL default '',
  "display_name" varchar(100) NOT NULL default '',
  "address" varchar(75) NOT NULL default '',
  "check_interval" double precision NOT NULL default '0',
  "retry_interval" double precision NOT NULL default '0',
  "max_check_attempts" smallint NOT NULL default '0',
  "first_notification_delay" double precision NOT NULL default '0',
  "notification_interval" double precision NOT NULL default '0',
  "status_update_time" int NOT NULL,
  "output" text NOT NULL,
  "perf_data" text NOT NULL,
  "current_state" smallint NOT NULL default '0',
  "has_been_checked" smallint NOT NULL default '0',
  "should_be_scheduled" smallint NOT NULL default '0',
  "current_check_attempt" smallint NOT NULL default '0',
  "last_check" int NOT NULL,
  "next_check" int NOT NULL,
  "check_type" smallint NOT NULL default '0',
  "last_state_change" int NOT NULL,
  "last_hard_state_change" int NOT NULL,
  "last_hard_state" smallint NOT NULL default '0',
  "last_time_up" int NOT NULL,
  "last_time_down" int NOT NULL,
  "last_time_unreachable" int NOT NULL,
  "state_type" smallint NOT NULL default '0',
  "last_notification" int NOT NULL,
  "next_notification" int NOT NULL,
  "no_more_notifications" smallint NOT NULL default '0',
  "notifications_enabled" smallint NOT NULL default '0',
  "problem_has_been_acknowledged" smallint NOT NULL default '0',
  "acknowledgement_type" smallint NOT NULL default '0',
  "current_notification_number" smallint NOT NULL default '0',
  "passive_checks_enabled" smallint NOT NULL default '0',
  "active_checks_enabled" smallint NOT NULL default '0',
  "event_handler_enabled" smallint NOT NULL default '0',
  "flap_detection_enabled" smallint NOT NULL default '0',
  "is_flapping" smallint NOT NULL default '0',
  "percent_state_change" double precision NOT NULL default '0',
  "latency" double precision NOT NULL default '0',
  "execution_time" double precision NOT NULL default '0',
  "scheduled_downtime_depth" smallint NOT NULL default '0',
  "failure_prediction_enabled" smallint NOT NULL default '0',
  "process_performance_data" smallint NOT NULL default '0',
  "obsess_over_host" smallint NOT NULL default '0',
  "modified_attributes" int NOT NULL default '0',
  "event_handler" varchar(255) NOT NULL default '',
  "check_command" text NOT NULL,
  "notes" varchar(255) default NULL,
  "notes_url" varchar(255) default NULL,
  "action_url" varchar(255) default NULL,
  "icon_image" varchar(255) default NULL,
  "icon_image_alt" varchar(255) default NULL,
  "vrml_image" varchar(255) default NULL,
  "statusmap_image" varchar(255) default NULL,
  "have_2d_coords" smallint NOT NULL default '0',
  "x_2d" smallint NOT NULL default '0',
  "y_2d" smallint NOT NULL default '0',
  "notify_on_down" smallint NOT NULL default '0',
  "notify_on_unreachable" smallint NOT NULL default '0',
  "notify_on_recovery" smallint NOT NULL default '0',
  "notify_on_flapping" smallint NOT NULL default '0',
  "notify_on_downtime" smallint NOT NULL default '0',
  "stalk_on_up" smallint NOT NULL default '0',
  "stalk_on_down" smallint NOT NULL default '0',
  "stalk_on_unreachable" smallint NOT NULL default '0',
  "flap_detection_on_up" smallint NOT NULL default '0',
  "flap_detection_on_down" smallint NOT NULL default '0',
  "flap_detection_on_unreachable" smallint NOT NULL default '0',
  "low_flap_threshold" double precision NOT NULL default '0',
  "high_flap_threshold" double precision NOT NULL default '0',
  "freshness_threshold" smallint NOT NULL default '0',
  "retain_status_information" smallint NOT NULL default '0',
  "retain_nonstatus_information" smallint NOT NULL default '0',
  PRIMARY KEY ("id"),
  UNIQUE ("instance_id","host_name")
);
CREATE TABLE "hostgroups" (
  "id" serial,
  "alias" varchar(255) NOT NULL default '',
  "name" varchar(255) NOT NULL default '',
  "enabled" boolean NOT NULL default '0',
  PRIMARY KEY ("id")
);
CREATE TABLE "hostgroups_members" (
  "hostgroup_id" smallint  NOT NULL default '0',
  "host_id" smallint  default NULL,
  "hostgroup_child_id" smallint default NULL,
  PRIMARY KEY  ("hostgroup_id")
);
CREATE TABLE "hosts_commands" (
  "host_id" smallint  NOT NULL default '0',
  "check_command" text,
  "event_handler_command" text,
  PRIMARY KEY  ("host_id")
);
CREATE TABLE "hosts_parenthosts" (
  "host_id" int NOT NULL default '0',
  "host_child_id" int NOT NULL default '0',
  UNIQUE ("host_id","host_child_id")
);
CREATE TABLE "instances" (
  "id" serial,
  "instance_name" varchar(64) NOT NULL default '',
  "instance_description" varchar(128) NOT NULL default '',
  "instance_address" varchar(120) default NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "processevents" (
  "id" serial,
  "instance_id" smallint NOT NULL default '0',
  "event_type" smallint NOT NULL default '0',
  "event_time" int NOT NULL,
  "event_time_usec" int NOT NULL default '0',
  "process_id" int NOT NULL default '0',
  "program_name" varchar(16) NOT NULL default '',
  "program_version" varchar(20) NOT NULL default '',
  "program_date" varchar(10) NOT NULL default '',
  PRIMARY KEY ("id")
);
CREATE TABLE "program_status" (
  "instance_id" int NOT NULL default '0',
  "status_update_time" int NOT NULL,
  "program_start_time" int NOT NULL,
  "program_end_time" int NOT NULL,
  "is_currently_running" smallint NOT NULL default '0',
  "pid" int NOT NULL default '0',
  "daemon_mode" smallint NOT NULL default '0',
  "last_command_check" int NOT NULL,
  "last_log_rotation" int NOT NULL,
  "notifications_enabled" smallint NOT NULL default '0',
  "active_service_checks_enabled" smallint NOT NULL default '0',
  "passive_service_checks_enabled" smallint NOT NULL default '0',
  "active_host_checks_enabled" smallint NOT NULL default '0',
  "passive_host_checks_enabled" smallint NOT NULL default '0',
  "event_handlers_enabled" smallint NOT NULL default '0',
  "flap_detection_enabled" smallint NOT NULL default '0',
  "failure_prediction_enabled" smallint NOT NULL default '0',
  "process_performance_data" smallint NOT NULL default '0',
  "obsess_over_hosts" smallint NOT NULL default '0',
  "obsess_over_services" smallint NOT NULL default '0',
  "modified_host_attributes" int NOT NULL default '0',
  "modified_service_attributes" int NOT NULL default '0',
  "global_host_event_handler" text NOT NULL,
  "global_service_event_handler" text NOT NULL,
  PRIMARY KEY ("instance_id")
);
CREATE TABLE "scheduled_downtime" (
  "id" serial,
  "instance_id" int NOT NULL default '0',
  "downtime_type" smallint NOT NULL default '0',
  "host_id" smallint  default NULL,
  "service_id" smallint  default NULL,
  "entry_time" int NOT NULL,
  "author_name" varchar(255) NOT NULL default '',
  "comment_data" text NOT NULL,
  "internal_downtime_id" int NOT NULL default '0',
  "triggered_by" int NOT NULL default '0',
  "is_fixed" smallint NOT NULL default '0',
  "duration" smallint NOT NULL default '0',
  "start_time" int NOT NULL,
  "end_time" int NOT NULL,
  "was_started" smallint NOT NULL default '0',
  "actual_start_time" int NOT NULL,
  "actual_end_time" int NOT NULL,
  "was_cancelled" smallint NOT NULL default '0',
  PRIMARY KEY ("id")
);
CREATE TABLE "service" (
  "id" serial,
  "instance_id" int  default '0',
  "host_name" varchar(64)  default '',
  "service_description" varchar(160)  default '',
  "display_name" varchar(64)  default '',
  "status_update_time" int ,
  "check_interval" double precision  default '0',
  "retry_interval" double precision  default '0',
  "max_check_attempts" smallint  default '0',
  "current_check_attempt" smallint  default '0',
  "has_been_checked" smallint  default '0',
  "should_be_scheduled" smallint  default '0',
  "passive_checks_enabled" smallint  default '0',
  "active_checks_enabled" smallint  default '0',
  "current_state" smallint  default '0',
  "state_type" smallint  default '0',
  "output" varchar(255)  default '',
  "perf_data" text ,
  "last_check" int ,
  "next_check" int ,
  "check_type" smallint  default '0',
  "latency" double precision  default '0',
  "execution_time" double precision  default '0',
  "last_state_change" int ,
  "last_hard_state_change" int ,
  "last_hard_state" smallint  default '0',
  "last_time_ok" int ,
  "last_time_warning" int ,
  "last_time_unknown" int ,
  "last_time_critical" int ,
  "default_passive_checks_enabled" smallint  default '0',
  "default_active_checks_enabled" smallint  default '0',
  "last_notification" int ,
  "next_notification" int ,
  "no_more_notifications" smallint  default '0',
  "notifications_enabled" smallint  default '0',
  "default_notifications_enabled" smallint  default '0',
  "current_notification_number" smallint  default '0',
  "first_notification_delay" double precision  default '0',
  "notification_interval" double precision  default '0',
  "notify_on_warning" smallint  default '0',
  "notify_on_unknown" smallint  default '0',
  "notify_on_critical" smallint  default '0',
  "notify_on_recovery" smallint  default '0',
  "notify_on_flapping" smallint  default '0',
  "notify_on_downtime" smallint  default '0',
  "problem_has_been_acknowledged" smallint  default '0',
  "acknowledgement_type" smallint  default '0',
  "flap_detection_enabled" smallint  default '0',
  "default_flap_detection_enabled" smallint  default '0',
  "flap_detection_on_ok" smallint  default '0',
  "flap_detection_on_warning" smallint  default '0',
  "flap_detection_on_unknown" smallint  default '0',
  "flap_detection_on_critical" smallint  default '0',
  "is_flapping" smallint  default '0',
  "percent_state_change" double precision  default '0',
  "low_flap_threshold" double precision  default '0',
  "high_flap_threshold" double precision  default '0',
  "scheduled_downtime_depth" smallint  default '0',
  "default_failure_prediction_enabled" smallint  default '0',
  "process_performance_data" smallint  default '0',
  "default_process_performance_data" smallint  default '0',
  "obsess_over_service" smallint  default '0',
  "modified_attributes" int  default '0',
  "event_handler" varchar(255)  default '',
  "check_command" varchar(255)  default '',
  "stalk_on_ok" smallint  default '0',
  "stalk_on_warning" smallint  default '0',
  "stalk_on_unknown" smallint  default '0',
  "stalk_on_critical" smallint  default '0',
  "is_volatile" smallint  default '0',
  "event_handler_enabled" smallint  default '0',
  "default_event_handler_enabled" smallint  default '0',
  "freshness_checks_enabled" smallint  default '0',
  "freshness_threshold" smallint  default '0',
  "retain_status_information" smallint  default '0',
  "retain_nonstatus_information" smallint  default '0',
  "failure_prediction_enabled" smallint  default '0',
  "failure_prediction_options" varchar(64)  default '',
  "notes" varchar(255) default NULL,
  "notes_url" varchar(255) default NULL,
  "action_url" varchar(255) default NULL,
  "icon_image" varchar(255) default NULL,
  "icon_image_alt" varchar(255) default NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("instance_id","host_name","service_description")
);
CREATE TABLE "servicegroups" (
  "id" serial,
  "alias" varchar(255)  default '',
  "name" varchar(255)  default '',
  "enabled" boolean  default '0',
  PRIMARY KEY ("id")
);
CREATE TABLE "servicegroups_members" (
  "servicegroup_id" smallint   default '0',
  "service_id" smallint  default NULL,
  "servicegroup_child_id" smallint  default NULL,
  PRIMARY KEY  ("servicegroup_id")
);
CREATE TABLE "services_commands" (
  "service_id" smallint   default '0',
  "check_command" text,
  "event_handler_command" text,
  PRIMARY KEY  ("service_id")
);
