/*
** Pipeline code.
*/

stage('Dependencies containers creation') {
  parallel 'centos7 dependencies': {
    node {
      dir('centreon-broker-centos7') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build --no-cache . -f Dockerfile.broker-centos7-dependencies -t registry.centreon.com/centreon-broker-centos7-dependencies:21.10'
          sh 'docker push registry.centreon.com/centreon-broker-centos7-dependencies:21.10'
        }
      }
    }
  },
  'debian dependencies': {
    node {
      dir('centreon-broker-debian') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build --no-cache . -f Dockerfile.broker-debian-dependencies -t registry.centreon.com/centreon-broker-debian-dependencies:21.10'
          sh 'docker push registry.centreon.com/centreon-broker-debian-dependencies:21.10'
        }
      }
    }
  },
  'centos8 dependencies': {
    node {
      dir('centreon-broker-centos8') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build . -f Dockerfile.broker-centos8-dependencies -t registry.centreon.com/centreon-broker-centos8-dependencies:21.10'
          sh 'docker push registry.centreon.com/centreon-broker-centos8-dependencies:21.10'
        }
      }
    }
  }
}